<!doctype html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <title>Login</title>
        <meta content="width=device-width, initial-scale=1" name="viewport">
        <link id="bootstrap-css" rel="stylesheet" href="css/bootstrap.min.css">
        <style type="text/css">
            .form-signin
            {
                max-width: 330px;
                padding: 15px;
                margin: 0 auto;
            }
            .form-signin .form-signin-heading, .form-signin .checkbox
            {
                margin-bottom: 10px;
            }
            .form-signin .checkbox
            {
                font-weight: normal;
            }
            .form-signin .form-control
            {
                position: relative;
                font-size: 16px;
                height: auto;
                padding: 10px;
                -webkit-box-sizing: border-box;
                -moz-box-sizing: border-box;
                box-sizing: border-box;
            }
            .form-signin .form-control:focus
            {
                z-index: 2;
            }
            .form-signin input[type="text"]
            {
                margin-bottom: -1px;
                border-bottom-left-radius: 0;
                border-bottom-right-radius: 0;
            }
            .form-signin input[type="password"]
            {
                margin-bottom: 10px;
                border-top-left-radius: 0;
                border-top-right-radius: 0;
            }
            .account-wall
            {
                margin-top: 20px;
                padding: 40px 0px 20px 0px;
                background-color: #f7f7f7;
                -moz-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
                -webkit-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
                box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
            }
            .login-title
            {
                color: #555;
                font-size: 18px;
                font-weight: 400;
                display: block;
            }
            .profile-img
            {
                width: 96px;
                height: 96px;
                margin: 0 auto 10px;
                display: block;
                -moz-border-radius: 50%;
                -webkit-border-radius: 50%;
                border-radius: 50%;
            }
            .need-help
            {
                margin-top: 10px;
            }
            .new-account
            {
                display: block;
                margin-top: 10px;
            }  
            .modal-header-primary
            {
                color:#fff;
                padding:9px 15px;
                border-bottom:1px solid #eee;
                background-color: #428bca;
                -webkit-border-top-left-radius: 5px;
                -webkit-border-top-right-radius: 5px;
                -moz-border-radius-topleft: 5px;
                -moz-border-radius-topright: 5px;
                 border-top-left-radius: 5px;
                 border-top-right-radius: 5px;
            }
        </style>
        <script src="js/jquery-1.10.2.min.js"></script>
        <script src="js/bootstrap.min.js"></script>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-md-4 col-md-offset-4">
                    <h1 class="text-center login-title">Login - CRUD</h1>
                    <div class="account-wall">
                        <img alt="" src="https://lh5.googleusercontent.com/-b0-k99FZlyE/AAAAAAAAAAI/AAAAAAAAAAA/eu7opA4byxI/photo.jpg?sz=120" class="profile-img">
                        <form class="form-signin" method="post" action="./usuario/entrar">
                            <input type="text" name="login" autofocus=""  placeholder="Login" class="form-control">
                            <input type="password" name="senha"  placeholder="Senha" class="form-control">
                            <button type="submit" class="btn btn-lg btn-primary btn-block">Fazer login</button>
                        </form>
                    </div>
                    <a class="text-center new-account" data-toggle="modal" href="#primary">Criar uma conta</a>
                </div>
            </div>
        </div>	

        <div class="container">
            <!-- Modal -->
            <div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="primary" class="modal fade" style="display: none;">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header modal-header-primary">
                            <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
                            <h1><i class="glyphicon glyphicon-thumbs-up"></i> Criar Conta!</h1>
                        </div>
                        <form method="post" action="./usuario/cadastrar">
                            <div class="modal-body">
                                <div class="form-group">
                                    <input type="text" class="form-control " name="nome" placeholder="Nome">
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control " name="login" placeholder="Login">
                                </div>
                                <div class="input-group">
                                    <input type="password" class="form-control pwd" name="senha" placeholder="Senha">
                                    <span class="input-group-btn">
                                        <button type="button" class="btn btn-default revela"><i class="glyphicon glyphicon-eye-open"></i></button>
                                    </span>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-ok-sign"></span>&nbsp;Cadastrar</button>
                            </div>
                        </form>
                    </div><!-- /.modal-content -->
                </div><!-- /.modal-dialog -->
            </div><!-- /.modal -->
        </div>
        <script>
            $(".revela").mousedown(
                function() {
                    $(".pwd").replaceWith($('.pwd').clone().attr('type', 'text'));
                }
            )
            .mouseup(
                function() {
                    $(".pwd").replaceWith($('.pwd').clone().attr('type', 'password'));
                }
            )
            .mouseout(
                function() {
                    $(".pwd").replaceWith($('.pwd').clone().attr('type', 'password'));
                }
            );
        </script>
    </body>
</html>